/* USUARIOS */
INSERT INTO USUARIO (NOMBRE, APELLIDO, EDAD, GENERO, 
    PESO, ESTATURA, TIPO, NICKNAME, CONTRASENIA) 
    VALUES ('Dan', 'Reynolds', 33, 1, 170.00, 1.95, 0, 'dare', '1234');
    
INSERT INTO USUARIO (NOMBRE, APELLIDO, EDAD, GENERO, 
        PESO, ESTATURA, TIPO, NICKNAME, CONTRASENIA) 
    VALUES ('Damien', 'Rice', 47, 1, 150.00, 1.80, 0, 'dari', '1234');

INSERT INTO USUARIO (NOMBRE, APELLIDO, EDAD, GENERO, 
        PESO, ESTATURA, TIPO, NICKNAME, CONTRASENIA) 
    VALUES ('Avril', 'Lavigne', 36 , 0, 110.23, 1.57, 0, 'avla', '1234');

INSERT INTO USUARIO (NOMBRE, APELLIDO, EDAD, GENERO, 
        PESO, ESTATURA, TIPO, NICKNAME, CONTRASENIA) 
    VALUES ('Robert', 'Lewandowski', 32, 1, 176.37, 1.84, 0, 'rolew', '1234');

INSERT INTO USUARIO (NOMBRE, APELLIDO, EDAD, GENERO, 
        PESO, ESTATURA, TIPO, NICKNAME, CONTRASENIA) 
    VALUES ('Jurgen', 'Klopp', 53, 1, 182.98, 1.91, 1, 'jukl', '1234');

INSERT INTO USUARIO (NOMBRE, APELLIDO, EDAD, GENERO, 
        PESO, ESTATURA, TIPO, NICKNAME, CONTRASENIA) 
    VALUES ('Alex', 'Morgan', 31, 0, 136.68, 1.70, 1, 'almo', '1234');